const actionsTypes = {
    FETCH_MOVIES_LIST: 'FETCH_MOVIES_LIST',
    FETCH_MOVIES_SORT_DOCUMENTARY: 'FETCH_MOVIES_SORT_DOCUMENTARY',
    FETCH_MOVIES_SORT_COMEDY: 'FETCH_MOVIES_SORT_COMEDY',
    FETCH_MOVIES_SORT_HORROR: 'FETCH_MOVIES_SORT_HORROR',
    FETCH_MOVIES_SORT_CRIME: 'FETCH_MOVIES_SORT_CRIME',
    POST_ADD_MOVIE: 'POST_ADD_MOVIE',
    PUT_UPDATE_MOVIE: 'PUT_UPDATE_MOVIE',

}

export default actionsTypes