const actionsTypes = {
    FETCH_MOVIES_LIST: 'FETCH_MOVIES_LIST',
    SHOW_MOVIES: 'SHOW_MOVIES',
    SHOW_MOVIES_SORT_DOCUMENTARY: 'SHOW_MOVIES_SORT_DOCUMENTARY',
    SHOW_MOVIES_SORT_COMEDY: 'SHOW_MOVIES_SORT_COMEDY',
    SHOW_MOVIES_SORT_HORROR: 'SHOW_MOVIES_SORT_HORROR',
    SHOW_MOVIES_SORT_CRIME: 'SHOW_MOVIES_SORT_CRIME',
    GET_MOVIE_BY_ID: 'GET_MOVIE_BY_ID',
    POST_ADD_MOVIE: 'POST_ADD_MOVIE',
    PUT_UPDATE_MOVIE: 'PUT_UPDATE_MOVIE',

}

export default actionsTypes